### ISSUE TITLE
Handle nonexistent packages gracefully

### ISSUE THREAD

**Issue by myint** [treyhunner/pep438#4]
``` bash
$ pep438 abcdefghijklmnopqrstuvwxyz0123456789
Traceback (most recent call last):
  File "/Users/myint/Library/Python/3.3/bin/pep438", line 9, in <module>
    load_entry_point('pep438==0.2.0', 'console_scripts', 'pep438')()
  File "/Users/myint/Library/Python/3.3/lib/python/site-packages/pep438/main.py", line 81, in main
    links = get_links(package)
  File "/Users/myint/Library/Python/3.3/lib/python/site-packages/pep438/core.py", line 12, in get_links
    response.raise_for_status()
  File "/Users/myint/Library/Python/3.3/lib/python/site-packages/requests/models.py", line 670, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found (abcdefghijklmnopqrstuvwxyz0123456789 does not have any releases)
```

I would expect something like,

``` bash
$ pep438 abcdefghijklmnopqrstuvwxyz0123456789
abcdefghijklmnopqrstuvwxyz0123456789 does not exist
```

with a nonzero exit status.

**Comment by treyhunner** [comment]
I agree, this is a bug.

Some things I'm not sure about yet, implementation-wise:

Should the package checking completely halt when a bad package name is found or should it continue to check other packages?  If it doesn't immediately halt (as it does now) should the exit status be non-zero still?

Pull requests for failing test or working implementation welcome.

**Comment by myint** [comment]
I'm not sure which is better, but I think it should exit with a nonzero exit status either way.

What I did to notice this error was to go into my `projects` directory and run `pep438 *`. (Some may consider this an edge case. And I can easily work around this with `$ ls | parallel pep438`.)

**Comment by treyhunner** [comment]
`pep438 *` would be more useful if pep438 noticed directories and parsed `setup.py` files.  That could be a useful feature also.

I think packages should continue to be checked and the error messages should be printed to `stderr`.  That way `pep438 *` would still work for all directories that have recognized package names and errors could easily be ignored.
